In [1]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv(r"C:\Users\lenovo\OneDrive\Desktop\data science\sample data\titanic.csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
df.shape

(418, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [9]:
null_count=df.isnull().sum()

In [11]:
null_count

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [18]:
numeric_columns = df.select_dtypes(include=np.number).columns

range_report = pd.DataFrame({
    "Minimum": df[numeric_columns].min(),
    "Maximum": df[numeric_columns].max()
})

range_report

             Minimum    Maximum
PassengerId   892.00  1309.0000
Survived        0.00     1.0000
Pclass          1.00     3.0000
Age             0.17    76.0000
SibSp           0.00     8.0000
Parch           0.00     9.0000
Fare            0.00   512.3292

In [21]:
df["Survived"].unique()

array([0, 1])

In [22]:
df['Pclass'].unique()

array([3, 2, 1])

In [23]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [25]:
df['Embarked'].unique()

array(['Q', 'S', 'C'], dtype=object)

In [26]:
expected_types = {
    "PassengerId": "string",
    "Survived": "int64",
    "Pclass": "int64",
    "Name": "object",
    "Sex": "object",
    "Age": "float64",
    "SibSp": "int64",
    "Parch": "int64",
    "Ticket": "object",
    "Fare": "float64",
    "Cabin": "object",
    "Embarked": "object"
}

dtype_report = pd.DataFrame({
    "Actual Type": df.dtypes.astype(str),
    "Expected Type": pd.Series(expected_types)
})

dtype_report["Correct"] = (
    dtype_report["Actual Type"] == dtype_report["Expected Type"]
)

dtype_report

            Actual Type Expected Type  Correct
PassengerId       int64        string    False
Survived          int64         int64     True
Pclass            int64         int64     True
Name             object        object     True
Sex              object        object     True
Age             float64       float64     True
SibSp             int64         int64     True
Parch             int64         int64     True
Ticket           object        object     True
Fare            float64       float64     True
Cabin            object        object     True
Embarked         object        object     True

In [27]:
quality_report = pd.DataFrame({
    "Null Count": df.isnull().sum(),
    "Data Type": df.dtypes.astype(str),
    "Unique Values": df.nunique(),
    "Minimum": df.min(numeric_only=True),
    "Maximum": df.max(numeric_only=True)
})

quality_report

             Null Count Data Type  Unique Values  Minimum    Maximum
Age                  86   float64             79     0.17    76.0000
Cabin               327    object             76      NaN        NaN
Embarked              0    object              3      NaN        NaN
Fare                  1   float64            169     0.00   512.3292
Name                  0    object            418      NaN        NaN
Parch                 0     int64              8     0.00     9.0000
PassengerId           0     int64            418   892.00  1309.0000
Pclass                0     int64              3     1.00     3.0000
Sex                   0    object              2      NaN        NaN
SibSp                 0     int64              7     0.00     8.0000
Survived              0     int64              2     0.00     1.0000
Ticket                0    object            363      NaN        NaN

# Missing values found in Age, Fare, and Cabin.
# No duplicate rows are present.
# PassengerId will be converted from integer to string.
# Numeric ranges will be checked for anomalies.

In [28]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [29]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [30]:
df["Fare"] = df["Fare"].fillna(df["Fare"].median())

In [31]:
df["Cabin"] = df["Cabin"].fillna(df["Cabin"].mode()[0])

In [32]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# Age: Missing values replaced with the median.
# Fare: Missing value replaced with the median due to high values.
# Cabin: Missing values replaced using the mode.
# Cabin: High number of missing values should be considered in further analysis.

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df = df.drop_duplicates()    # no duplicates

# Duplicate rows: Checked before cleaning.
# Result: No duplicate rows were found.
# Action: No records were removed.

In [36]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,B57 B59 B63 B66,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,B57 B59 B63 B66,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,B57 B59 B63 B66,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,B57 B59 B63 B66,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,B57 B59 B63 B66,C

In [37]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [38]:
df['Embarked'].unique()

array(['Q', 'S', 'C'], dtype=object)

In [39]:
df["Sex"] = df["Sex"].astype(str).str.strip().str.lower()

In [40]:
df["Embarked"] = df["Embarked"].astype(str).str.strip().str.upper()

In [41]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,B57 B59 B63 B66,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,B57 B59 B63 B66,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,B57 B59 B63 B66,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,B57 B59 B63 B66,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,B57 B59 B63 B66,C

In [42]:
df["Sex"].unique()

array(['male', 'female'], dtype=object)

In [43]:
df["Embarked"].unique()

array(['Q', 'S', 'C'], dtype=object)

# Sex and Embarked: Standardized for consistency.
# Removed unnecessary spaces.
# Converted values into a consistent format.
# Data was already mostly consistent, so only minor cleaning was needed.

# This data does not contain and date , so date conversinon is not require

In [46]:
numeric_columns = df.select_dtypes(include=np.number).columns

In [47]:
numeric_columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [48]:
outlier_report = []

for col in numeric_columns:
    Q1 = df[col].quantile(0.25)   # 25%
    Q3 = df[col].quantile(0.75)   # 75%
    
    IQR = Q3 - Q1   # formula
    
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower_limit) | (df[col] > upper_limit)]
    
    outlier_report.append([
        col,
        Q1,
        Q3,
        lower_limit,
        upper_limit,
        len(outliers)
    ])

outlier_report = pd.DataFrame(
    outlier_report,
    columns=[
        "Column",
        "Q1",
        "Q3",
        "Lower Limit",
        "Upper Limit",
        "Outlier Count"
    ]
)

outlier_report

        Column        Q1           Q3  Lower Limit  Upper Limit  Outlier Count
0  PassengerId  996.2500  1204.750000   683.500000  1517.500000              0
1     Survived    0.0000     1.000000    -1.500000     2.500000              0
2       Pclass    1.0000     3.000000    -2.000000     6.000000              0
3          Age   23.0000    35.750000     3.875000    54.875000             36
4        SibSp    0.0000     1.000000    -1.500000     2.500000             11
5        Parch    0.0000     0.000000     0.000000     0.000000             94
6         Fare    7.8958    31.471875   -27.468312    66.835988             55

In [50]:
for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower_limit) | (df[col] > upper_limit)][col]

# IQR method: Used to identify outliers in numeric columns.
# Outliers found: Age, SibSp, Parch, and Fare.
# Decision: Outliers were retained as they may represent valid data.
# Reason: Removing or capping them could cause loss of useful information.

In [51]:
df["PassengerId"] = df["PassengerId"].astype("string")

In [52]:
df["Survived"] = df["Survived"].astype("int64")
df["Pclass"] = df["Pclass"].astype("int64")
df["Age"] = df["Age"].astype("float64")
df["SibSp"] = df["SibSp"].astype("int64")
df["Parch"] = df["Parch"].astype("int64")
df["Fare"] = df["Fare"].astype("float64")

In [53]:
df.dtypes

PassengerId    string[python]
Survived                int64
Pclass                  int64
Name                   object
Sex                    object
Age                   float64
SibSp                   int64
Parch                   int64
Ticket                 object
Fare                  float64
Cabin                  object
Embarked               object
dtype: object

In [54]:
dtype_accuracy = {
    "PassengerId": "string",
    "Survived": "int64",
    "Pclass": "int64",
    "Name": "object",
    "Sex": "object",
    "Age": "float64",
    "SibSp": "int64",
    "Parch": "int64",
    "Ticket": "object",
    "Fare": "float64",
    "Cabin": "object",
    "Embarked": "object"
}

correct_dtypes = 0

for col, expected in dtype_accuracy.items():
    if str(df[col].dtype) == expected:
        correct_dtypes += 1

print("Correct data types:", correct_dtypes)
print("Total columns:", len(dtype_accuracy))

Correct data types: 12
Total columns: 12

# PassengerId: Converted from integer to string as it is an identifier.
# Age and Fare: Stored as float values.
# Survived, Pclass, SibSp, Parch: Stored as integers.
# Categorical columns: Kept as object/string type.

In [58]:
# Before cleaning

original_df = pd.read_csv(r'C:\Users\lenovo\OneDrive\Desktop\data science\sample data\titanic.csv')

before_null_count = original_df.isnull().sum().sum()
before_duplicate_count = original_df.duplicated().sum()
before_row_count = len(original_df)

before_dtype_accuracy = sum(
    str(original_df[col].dtype) == expected
    for col, expected in dtype_accuracy.items()
)


# After cleaning

after_null_count = df.isnull().sum().sum()
after_duplicate_count = df.duplicated().sum()
after_row_count = len(df)

after_dtype_accuracy = sum(
    str(df[col].dtype) == expected
    for col, expected in dtype_accuracy.items()
)

In [59]:
summary = pd.DataFrame({
    "Metric": [
        "Null Count",
        "Duplicate Count",
        "Row Count",
        "Correct Dtype Count"
    ],
    
    "Before Cleaning": [
        before_null_count,
        before_duplicate_count,
        before_row_count,
        before_dtype_accuracy
    ],
    
    "After Cleaning": [
        after_null_count,
        after_duplicate_count,
        after_row_count,
        after_dtype_accuracy
    ]
})

summary

                Metric  Before Cleaning  After Cleaning
0           Null Count              414               0
1      Duplicate Count                0               0
2            Row Count              418             418
3  Correct Dtype Count               11              12

# Missing values: Handled during cleaning.
# Duplicates: Checked and no duplicate records were found.
# Row count: Maintained after cleaning.
# Data types: Corrected where necessary.
# Overall: The cleaning process improved data quality and consistency.

In [60]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,B57 B59 B63 B66,S

In [61]:
df.to_csv("titanic_cleaned.csv", index=False)